src/auth/index.js
=> Toast alert when .env properties are missing

src/components/BigCalendarFull/index.jsx, src/components/BigCalendarFull/index.scss, src/components/DatePicker/index.jsx, src/scss/utils/utilities.scss
=> fixed #75 not show year on firefox, fixed #68 format time incorrect

src/components/ComponentDatepicker/index.jsx, src/components/Inspiration/index.jsx, src/components/Table/GlobalFilter.jsx, src/components/Table/index.jsx, src/containers/CampaignsPage/CampaignsList/CampaignsList.jsx, src/containers/ContentPage/ContentsList/ContentsList.jsx, src/containers/ProjectsPage/ProjectsList/ProjectsList.jsx
=> fixed #85 Show wrong placeholder and clear filter when change tabs, fixed #53 datepicker close every click

src/components/BigCalendarFull/index.jsx, src/components/BigCalendarFull/index.scss, src/components/Table/index.jsx
=> fixed #51 style event of calendar & fix change thumb view

src/components/Table/PaginationComponent.jsx, src/containers/ProjectsPage/ProjectViewModels/ProjectsListViewModel.js
=> fixed #91 style pagination, fixed #92 number of project per page

src/components/DatePicker/index.jsx, src/containers/ContentPage/ContentViewModels/ContentFormViewModel.js, src/utils/form.js
=>  fixed #86 cannot edit when over limit post, #97 cannot update when change birth day

src/containers/ContentPage/ContentViewModels/ContentFormViewModel.js
=> fixed #86 user can create post when over post limit

src/components/BigCalendarFull/index.jsx, src/components/ComponentDatepicker/index.jsx, src/components/Menu/index.jsx, src/components/Menu2/index.jsx, src/components/SbarLeft/index.jsx, src/translations/dk/common.json, src/translations/en/common.json, src/translations/es/common.json, src/translations/i18n.js, src/translations/ua/common.json, src/translations/vi/common.json
Fixed #105  and #50 translate text more
=> Sync Translate Language for Dashboard and Profile

src/components/BigCalendarFull/index.jsx, src/translations/th/common.json
=> fixed #119 Thai language

src/translations/th/common.json
update thai language for v.1.5.0
=> update Thai language for v.1.5.0

src/components/CanvaButton/index.jsx, src/containers/ContentPage/ContentForm/ContentFormDescription/media.jsx, src/translations/dk/common.json, src/translations/en/common.json, src/translations/es/common.json, src/translations/th/common.json, src/translations/ua/common.json, src/translations/vi/common.json
=> #116 update Canva button

src/containers/ChannelsPage/LoginChannelCMSForm/LoginChannelCMSForm.jsx, src/containers/ChannelsPage/LoginChannelCMSForm/LoginChannelCMSFormModal.jsx
=> #141 Change a little things in joomla-connection pop-up

src/components/FilterCalendar/index.jsx, src/containers/CampaignsPage/CampaignsList/CampaignsList.jsx, src/translations/dk/common.json, src/translations/en/common.json, src/translations/es/common.json, src/translations/th/common.json, src/translations/ua/common.json, src/translations/vi/common.json
=> fixed #145 Campains loading, fixed #147 checkbox incorrect

package-lock.json, package.json
@jatitoam Because package-lock force old version of [aesirx-dma-lib](https://github.com/aesirxio/dma-lib) so it make loading don't stop when create post . So i update it to latest version of aesirx-dma-lib
=> fixes #136 Loading not stop

src/components/Select/customStyles.js, src/components/Table/index.jsx, src/components/Table/index.scss, src/scss/utils/utilities.scss
=> fixed #146 cannot select item filter

src/containers/CampaignsPage/CampaignsList/CampaignsList.jsx, src/containers/ContentPage/ContentsList/ContentsList.jsx
=> fixed #156 filter not work

src/containers/ChannelsPage/LoginChannelCMSForm/LoginChannelCMSFormJoomla.jsx, src/containers/ChannelsPage/LoginChannelCMSForm/LoginChannelCMSFormModal.jsx
=> #141  Channel - Joomla - Popup connect

src/components/Header/index.jsx, src/components/Header/index.scss, src/components/SbarLeft/index.jsx, src/components/SwitchThemes/index.jsx, src/components/SwitchThemes/index.scss, src/themes/dark.scss, src/themes/themes.scss
=> #144 Update dark mode

src/components/FilterCalendar/index.jsx
=> fixes #186

src/components/Header/index.jsx, src/components/SbarLeft/index.jsx, src/scss/app.scss
=> #175 Window 10 - HP EliteBook - Chrome - The text too long

src/containers/LoginPage/index.jsx, src/containers/LoginPage/index.scss
=> Login app - Change the basic style

src/scss/utils/atomic.scss
=> the overlay override on left menu

package-lock.json, package.json, src/containers/ContentPage/ContentViewModels/ContentFormViewModel.js, src/containers/WizardPage/index.jsx, src/routes/routes.js
=> Create post - Remove wizard in the link

src/components/Menu/index.scss
=> Left Menu - Change the bold text when user active item

src/containers/LoginPage/index.jsx
=> #174 update 

src/constants/CampaignsModule.js, src/containers/CampaignsPage/CampaignsList/CampaignsList.jsx, src/containers/CampaignsPage/CampaignsModel/CampaignsModel.js
=> fix campaign page

package.json, src/components/ComponentDatepicker/index.jsx, src/components/ComponentFilter/index.jsx, src/components/Table/index.jsx, src/scss/utils/atomic.scss
=> fixes #245 Hover affects are not same

src/containers/CampaignsPage/CampaignsViewModels/CampaignsFormModalViewModel.js, src/containers/ProjectsPage/ProjectViewModels/ProjectFormModalViewModel.js
=> fixes #234 Create Project - Add message successful

package.json, public/assets/images/calendar.svg, src/components/ComponentDatepicker/index.jsx, src/components/ComponentDatepicker/index.scss, src/components/ComponentSVG/index.jsx, src/components/Header/index.jsx, src/components/Table/index.jsx, src/scss/utils/atomic.scss, src/themes/index.scss, src/translations/dk/common.json, src/translations/en/common.json, src/translations/es/common.json, src/translations/th/common.json, src/translations/ua/common.json, src/translations/vi/common.json, yarn.lock
=> fixes #251 UI - Campaign, Content - Style the filter date

src/containers/ContentPage/ContentModel/ContentModel.js
=> fixes #90 Content - The post select Publish is Schedule save the time create

src/containers/ContentPage/ContentsList/ContentsList.jsx
=> Fixes #332 Edit posts

src/components/ButtonShareLink.js, src/constants/ContentModule.js, src/containers/ContentPage/ContentModel/ContentChannelsModel.js, src/containers/ContentPage/ContentModel/ContentModel.js, src/containers/ContentPage/ContentsList/ContentsList.jsx
=> Fixes #330 UTM link and #331 Share links

src/containers/WizardPage/index.jsx
=> Fixed #350 Click next button was redirect wrong url

src/containers/CampaignsPage/CampaignsForm/CampaignsActionBar.jsx, src/containers/ProjectsPage/ProjectForm/ProjectActionBar.jsx, src/containers/WizardPage/index.jsx
=> Fixed #344 Buttons are missing styling

src/containers/ContentPage/ContentForm/ContentFormGeneral/index.jsx, src/containers/ContentPage/ContentUtils/ContentUtils.js, src/containers/ContentPage/ContentsList/ContentsList.jsx, src/routes/routes.js
=> Fixed #354 Bug description in Advance Mode

src/containers/ContentPage/ContentForm/ContentFormGeneral/index.jsx, src/routes/routes.js
=> Fixed #335 Bug connect channel and createPost missing image after click back button in Live

src/components/BigCalendarFull/CustomToolbar.jsx, src/translations/dk/common.json, src/translations/en/common.json, src/translations/es/common.json, src/translations/fr/common.json, src/translations/hr/common.json, src/translations/th/common.json, src/translations/ua/common.json, src/translations/vi/common.json
=> Fixed #362 Calendar - Click to Add new Post on that day

src/containers/CampaignsPage/CampaignsViewModels/CampaignsListViewModel.js
=> Fixes #380 Bug on the campaign

src/components/ComponentTooltip/index.jsx
=> Fixes #388 Show wrong channel name

packages/aesirx-dma-app/src/containers/ContentPage/ContentsList/ContentsList.jsx, packages/aesirx-dma-app/src/containers/ProjectsPage/ProjectsList/ProjectsList.jsx
=> Fixes #409 Get status Project DMA

packages/aesirx-dma-app/package.json, packages/aesirx-dma-app/src/components/Table/index.jsx, packages/aesirx-dma-app/tsup.config.ts
=> Fixed #414 change table by Uikit
